# Generated by Django 3.2.3 on 2021-06-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_agent_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='No Subject', max_length=80),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=858),
        ),
    ]
