# Generated by Django 3.2.3 on 2021-06-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='familyGameDev',
            field=models.TextField(choices=[('NINTENDO', 'Nintendo'), ('ROCKSTAR GAMES', 'Rockstar Games'), ('ID SOFTWARE', 'id Software'), ('UBISOFT', 'Ubisoft')]),
        ),
    ]
