# Generated by Django 3.2.3 on 2021-06-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210630_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='primeiro_nome',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='último_nome',
            new_name='last_name',
        ),
    ]
