# Generated by Django 3.2.3 on 2021-06-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210630_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='pokémon_Yellow_developer',
            new_name='pokemon_Yellow_developer',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='pokémon_Yellow_release_year',
            new_name='pokemon_Yellow_release_year',
        ),
    ]
