# Generated by Django 3.2.3 on 2021-07-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210701_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='phoneNum',
            new_name='phone_number',
        ),
    ]
