# Generated by Django 3.2.3 on 2021-07-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210701_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='agentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AgentID', to='website.agent'),
        ),
    ]
